### ISSUE TITLE
Superfluous isdirectory check?

### ISSUE THREAD

**Issue by xeruf** [DataWraith/auto_mkdir#1]
https://github.com/DataWraith/auto_mkdir/blob/377ea6fea37b952d18a5a34f7d5fe03d29e01219/plugin/auto_mkdir.vim#L48

Since `mkdir -p` ignores when the directory already exists, isn't that check superfluous, especially since the command itself will probably check that as well?

Other than that, thanks for this simple helper :)

**Comment by DataWraith** [comment]
Hi.

It's been 10 years since I last touched this code, but I think I had to put that in to deal with a corner case that otherwise caused trouble. I don't recall what it was though. It also might have been fixed in the intervening Vim releases.

I'm happy the plugin is still useful, but to be honest, I haven't used it myself in a long time; I merely keep it up just in case anyone still has it in their plugin manager so I don't cause breakage. Since the superfluous check isn't really a problem, I'm inclined to not change it to avoid the risk of breaking anything.
